Kori\KingdomServerBundle\Entity\Account:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      unique: true
      length: 255
    protection:
      type: integer
    gold:
      type: integer
      options:
        unsigned: true
        default: 0
    silver:
      type: integer
      options:
        unsigned: true
        default: 0
  manyToOne:
    kingdom:
      targetEntity: Kingdom
      inversedBy: goveners
      joinColumn:
        name: kingdom_id
        referencedColumnName: id




