Kori\KingdomServerBundle\Entity\Account:
  type: entity
  repositoryClass: Kori\KingdomServerBundle\Repository\AccountRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      unique: true
      length: 255
    protection:
      type: integer
    gold:
      type: integer
      options:
        unsigned: true
        default: 0
    silver:
      type: integer
      options:
        unsigned: true
        default: 0
  oneToOne:
    avatar:
      targetEntity: Avatar
      mappedBy: account
  manyToOne:
    kingdom:
      targetEntity: Kingdom
      inversedBy: goveners
      joinColumn:
        name: kingdom_id
        referencedColumnName: id
  oneToMany:
    towns:
      targetEntity: Town
      mappedBy: account




