Kori\KingdomServerBundle\Entity\BuildingType:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    uniqueInBase:
      type: boolean
  oneToMany:
    levels:
      targetEntity: BuildingLevel
      mappedBy: buildingType
