Kori\KingdomServerBundle\Entity\Message:
  type: entity
  repositoryClass: Kori\KingdomServerBundle\Repository\MessageRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    createdAt:
      type: integer
      options:
        unsigned: true
    subject:
      type: string
    message:
      type: string
  oneToOne:
    sender:
      targetEntity: Account
      joinColumn:
        name: sender_id
        referencedColumnName: id
    recipient:
      targetEntity: Account
      joinColumn:
        name: recipient_id
        referencedColumnName: id
