Kori\KingdomServerBundle\Entity\Quest:
  type: entity
  repositoryClass: Kori\KingdomServerBundle\Repository\QuestRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  oneToMany:
    steps:
      targetEntity: QuestStep
      mappedBy: quest
