Kori\KingdomServerBundle\Entity\Race:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  manyToMany:
    units:
      targetEntity: Unit
      joinTable:
        name: unit_race
        joinColumns:
          race_id:
            referencedColumnName: id
        inverseJoinColumns:
          unit_id:
            referencedColumnName: id
