Kori\KingdomServerBundle\Entity\TechnologyEffect:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    effect:
      type: string
    factor:
      type: float
  manyToOne:
    technologyLevel:
      targetEntity: TechnologyLevel
      inversedBy: effects
      joinColumn:
        name: technology_level_id
        referencedColumnName: id

