Kori\KingdomServerBundle\Entity\TechnologyLevel:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    level:
      type: integer
      options:
        unsigned: true
        length: 2
    affectAvatar:
      type: boolean
  oneToMany:
    effects:
      targetEntity: TechnologyEffect
      mappedBy: technologyLevel
  manyToOne:
    technology:
      targetEntity: Technology
      inversedBy: levels
      joinColumn:
        name: technology_id
        referencedColumnName: id
