Kori\KingdomServerBundle\Entity\Town:
  type: entity
  repositoryClass: Kori\KingdomServerBundle\Repository\TownRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    lastTick:
      type: integer
      options:
        unsigned: true
    wood:
      type: integer
      options:
        unsigned: true
    wheat:
      type: integer
      options:
        unsigned: true
    iron:
      type: integer
      options:
        unsigned: true
    clay:
      type: integer
      options:
        unsigned: true
  oneToOne:
    field:
      targetEntity: Field
      inversedBy: town
      joinColumn:
        name: field_id
        referencedColumnName: id
  manyToOne:
    account:
      targetEntity: Account
      inversedBy: towns
      joinColumn:
        name: account_id
        referencedColumnName: id
  manyToMany:
    units:
      targetEntity: TownUnits
      inversedBy: town
