Kori\KingdomServerBundle\Entity\TownUnits:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    count:
      type: integer
      options:
        unsigned: true
  manyToOne:
    town:
      targetEntity: Town
      inversedBy: units
      joinColumn:
        name: town_id
        referencedColumnName: id
  oneToOne:
    unit:
      targetEntity: Unit
      joinColumn:
        name: unit_id
        referencedColumnName: id
