services:
  Kori\KingdomServerBundle\Rules\Build\:
    resource: '../../Rules/Build/*'
    tags:
      - { name: kori_kingdom.build_rule }
  Kori\KingdomServerBundle\Rules\Attack\:
    resource: '../../Rules/Attack/*'
    tags:
      - { name: kori_kingdom.attack_rule }
  Kori\KingdomServerBundle\Rules\Influence\:
    resource: '../../Rules/Influence/*'
    tags:
      - { name: kori_kingdom.influence_rule }
