services:
  kori_kingdom.server_manager:
    class: Kori\KingdomServerBundle\Service\ServerManager
    public: true
  kori_kingdom.server:
    class: Kori\KingdomServerBundle\Service\Server
    factory: 'kori_kingdom.server_manager:matchDomain'
    public: true
    arguments:
      $requestStack: "@request_stack"
  kori_kingdom.generator_manager:
    class: Kori\KingdomServerBundle\Service\GeneratorManager
    public: false
  kori_kingdom.rule_manager:
    class: Kori\KingdomServerBundle\Service\RuleManager
    public: false
  kori_kingdom.effect_manager:
    class: Kori\KingdomServerBundle\Service\EffectManager
    public: false
  kori_kingdom.activity_manager:
    class: Kori\KingdomServerBundle\Service\ActivityManager
    public: true
    arguments:
      $serverManager: "@kori_kingdom.server_manager"
